### ISSUE TITLE
Issue with Canceling Already Canceled Stripe Subscription

### ISSUE THREAD

**Issue by tonydefaria** [pay-rails/pay#859] opened 2023-10-12 19:05 UTC
Description:

I encountered an issue in the Pay library when dealing with Stripe Subscriptions. The problem arises when a user cancels a Stripe Subscription but decides to keep their account, which still grants them access to resources not dependent on the subscription. Everything works as expected until the user decides to cancel their account entirely. At this point, I observed a "cus_xxxxxxxxxxx not found" error.

Upon investigation, it appears that the issue is related to the cancel_now!(**options) method. This method attempts to cancel a subscription even if it has already been marked as canceled in the Stripe system. This unnecessary cancellation attempt results in the error.

To resolve this issue, I have added a simple conditional check within the cancel_now! method. Before attempting to cancel the subscription, it verifies if the subscription is already in a canceled state. This check ensures that the cancellation process is only initiated when necessary, avoiding the "cus_xxxxxxxxxxx not found" error.

I have included the modified code snippet below:

```
def cancel_now!(**options)
  # Check if the subscription is already canceled
  if @stripe_subscription&.status != 'canceled'
    begin
      # Attempt to cancel the subscription only if it's not already canceled
      @stripe_subscription = ::Stripe::Subscription.cancel(processor_id, options.merge(expand_options), stripe_options)
    rescue ::Stripe::StripeError => e
      # Handle the case where the subscription is not found (already canceled)
      if e.message.include?('No such subscription')
        Rails.logger.debug "Subscription #{processor_id} is already canceled."
      else
        raise Pay::Stripe::Error, e
      end
    end
  else
    Rails.logger.debug "Subscription #{processor_id} is already canceled."
  end

  # Update the pay_subscription object
  pay_subscription.update(ends_at: Time.current, status: :canceled)
end
```
This modification resolved the issue and prevented unnecessary subscription cancellations.

I hope this information is helpful for improving the Pay library.

Have a good one,
T

**Comment by excid3** [comment] 2023-10-12 19:50
Can you provide a test case scenario that replicates the issue?

**Comment by tonydefaria** [comment] 2023-10-13 06:51
**Issue Description:**

1. I create a new user in my application.
2. The user subscribes to a plan via Stripe Checkout.
3. At some point, the user decides to cancel their subscription.
4. I advance the system clock to a day after the cancellation date.
5. Webhooks update the subscription status to "cancelled" in the Stripe dashboard and Pay Subscription.
6. Here comes the problem: When I attempt to cancel the entire user account in my application, I encounter the following error:
```
Pay::Stripe::Error in Users::RegistrationsController#destroy
No such subscription: 'sub_xxxxxxxxxxxxxxxxxxxxxx'
```
This error seems to be related to the previous subscription that was successfully canceled, but it still persists when attempting to cancel the user account.

**Environment:**

Rails 7.1
Devise 4.9
Pay 6.8
Stripe Checkout (for recurring setup)

I hope this information helps clarify the issue. I've already implemented a patch to address it, which resolved the problem. Unfortunately, I haven't written tests for the patch yet, as I'm not very experienced with unit testing.

I appreciate your support and apologise for any inconvenience this may cause. Please let me know if you need any further details or if there are specific actions I can take to assist in resolving this issue.

Thanks :)

**Comment by excid3** [comment] 2023-10-13 12:30
Thanks @tonydefaria.

What do you mean by "attempt to cancel the entire user account"? Can we have some code?

**Comment by tonydefaria** [comment] 2023-10-13 14:41
"attempt to cancel the entire user account"
I mean when you cancel an account using Devise.

**Comment by excid3** [comment] 2023-10-13 15:09
Ah, so basically `current_user.destroy`

Will take a look and see if I can reproduce.

**Comment by tonydefaria** [comment] 2023-10-13 15:12
@excid3 thank you so much! :)

**Comment by excid3** [comment] 2023-10-13 16:41
Can you send us the stacktrace as well?

**Comment by tonydefaria** [comment] 2023-10-13 17:20
`Pay::Stripe::Error in Users::RegistrationsController#destroy`

`No such subscription: 'sub_1O0oxBCychIMwryu4wSmW6WX'`

```
  pay_subscription.update(ends_at: Time.current, status: :canceled)
rescue ::Stripe::StripeError => e
  raise Pay::Stripe::Error, e
end

# This updates a SubscriptionItem's quantity in Stripe

```
```
[Application Trace](http://localhost:3000/account/edit#) | [Framework Trace](http://localhost:3000/account/edit#) | [Full Trace](http://localhost:3000/account/edit#)
[pay (6.8.1) lib/pay/stripe/subscription.rb:176:in `rescue in cancel_now!'](http://localhost:3000/account/edit#)
[pay (6.8.1) lib/pay/stripe/subscription.rb:172:in `cancel_now!'](http://localhost:3000/account/edit#)
[activesupport (7.1.0) lib/active_support/core_ext/module/delegation.rb:333:in `public_send'](http://localhost:3000/account/edit#)
[activesupport (7.1.0) lib/active_support/core_ext/module/delegation.rb:333:in `method_missing'](http://localhost:3000/account/edit#)
[activerecord (7.1.0) lib/active_record/relation/delegation.rb:100:in `each'](http://localhost:3000/account/edit#)
[activerecord (7.1.0) lib/active_record/relation/delegation.rb:100:in `each'](http://localhost:3000/account/edit#)
[pay (6.8.1) lib/pay/attributes.rb:63:in `cancel_active_pay_subscriptions!'](http://localhost:3000/account/edit#)
[activesupport (7.1.0) lib/active_support/callbacks.rb:403:in `block in make_lambda'](http://localhost:3000/account/edit#)
[activesupport (7.1.0) lib/active_support/callbacks.rb:264:in `block in conditional'](http://localhost:3000/account/edit#)
[activesupport (7.1.0) lib/active_support/callbacks.rb:602:in `block in invoke_after'](http://localhost:3000/account/edit#)
[activesupport (7.1.0) lib/active_support/callbacks.rb:602:in `each'](http://localhost:3000/account/edit#)
[activesupport (7.1.0) lib/active_support/callbacks.rb:602:in `invoke_after'](http://localhost:3000/account/edit#)
[activesupport (7.1.0) lib/active_support/callbacks.rb:111:in `run_callbacks'](http://localhost:3000/account/edit#)
[activesupport (7.1.0) lib/active_support/callbacks.rb:952:in `_run_commit_callbacks'](http://localhost:3000/account/edit#)
[activerecord (7.1.0) lib/active_record/transactions.rb:332:in `committed!'](http://localhost:3000/account/edit#)
[activerecord (7.1.0) lib/active_record/connection_adapters/abstract/transaction.rb:237:in `block in commit_records'](http://localhost:3000/account/edit#)
[activerecord (7.1.0) lib/active_record/connection_adapters/abstract/transaction.rb:263:in `run_action_on_records'](http://localhost:3000/account/edit#)
[activerecord (7.1.0) lib/active_record/connection_adapters/abstract/transaction.rb:236:in `commit_records'](http://localhost:3000/account/edit#)
[activerecord (7.1.0) lib/active_record/connection_adapters/abstract/transaction.rb:515:in `block in commit_transaction'](http://localhost:3000/account/edit#)
[activesupport (7.1.0) lib/active_support/concurrency/null_lock.rb:9:in `synchronize'](http://localhost:3000/account/edit#)
[activerecord (7.1.0) lib/active_record/connection_adapters/abstract/transaction.rb:503:in `commit_transaction'](http://localhost:3000/account/edit#)
[activerecord (7.1.0) lib/active_record/connection_adapters/abstract/transaction.rb:565:in `block in within_new_transaction'](http://localhost:3000/account/edit#)
[activesupport (7.1.0) lib/active_support/concurrency/null_lock.rb:9:in `synchronize'](http://localhost:3000/account/edit#)
[activerecord (7.1.0) lib/active_record/connection_adapters/abstract/transaction.rb:532:in `within_new_transaction'](http://localhost:3000/account/edit#)
[activerecord (7.1.0) lib/active_record/connection_adapters/abstract/database_statements.rb:342:in `transaction'](http://localhost:3000/account/edit#)
[activerecord (7.1.0) lib/active_record/transactions.rb:361:in `with_transaction_returning_status'](http://localhost:3000/account/edit#)
[activerecord (7.1.0) lib/active_record/transactions.rb:305:in `destroy'](http://localhost:3000/account/edit#)
[devise (4.9.2) app/controllers/devise/registrations_controller.rb:66:in `destroy'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/abstract_controller/base.rb:224:in `process_action'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/action_controller/metal/rendering.rb:165:in `process_action'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/abstract_controller/callbacks.rb:259:in `block in process_action'](http://localhost:3000/account/edit#)
[activesupport (7.1.0) lib/active_support/callbacks.rb:121:in `block in run_callbacks'](http://localhost:3000/account/edit#)
[actiontext (7.1.0) lib/action_text/rendering.rb:23:in `with_renderer'](http://localhost:3000/account/edit#)
[actiontext (7.1.0) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'](http://localhost:3000/account/edit#)
[activesupport (7.1.0) lib/active_support/callbacks.rb:130:in `instance_exec'](http://localhost:3000/account/edit#)
[activesupport (7.1.0) lib/active_support/callbacks.rb:130:in `block in run_callbacks'](http://localhost:3000/account/edit#)
[activesupport (7.1.0) lib/active_support/callbacks.rb:141:in `run_callbacks'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/abstract_controller/callbacks.rb:258:in `process_action'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/action_controller/metal/rescue.rb:25:in `process_action'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/action_controller/metal/instrumentation.rb:74:in `block in process_action'](http://localhost:3000/account/edit#)
[activesupport (7.1.0) lib/active_support/notifications.rb:206:in `block in instrument'](http://localhost:3000/account/edit#)
[activesupport (7.1.0) lib/active_support/notifications/instrumenter.rb:58:in `instrument'](http://localhost:3000/account/edit#)
[activesupport (7.1.0) lib/active_support/notifications.rb:206:in `instrument'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/action_controller/metal/instrumentation.rb:73:in `process_action'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/action_controller/metal/params_wrapper.rb:261:in `process_action'](http://localhost:3000/account/edit#)
[activerecord (7.1.0) lib/active_record/railties/controller_runtime.rb:32:in `process_action'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/abstract_controller/base.rb:160:in `process'](http://localhost:3000/account/edit#)
[actionview (7.1.0) lib/action_view/rendering.rb:40:in `process'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/action_controller/metal.rb:227:in `dispatch'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/action_controller/metal.rb:309:in `dispatch'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/action_dispatch/routing/route_set.rb:32:in `serve'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/action_dispatch/routing/mapper.rb:21:in `block in <class:Constraints>'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/action_dispatch/routing/mapper.rb:51:in `serve'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/action_dispatch/journey/router.rb:51:in `block in serve'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/action_dispatch/journey/router.rb:131:in `block in find_routes'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/action_dispatch/journey/router.rb:124:in `each'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/action_dispatch/journey/router.rb:124:in `find_routes'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/action_dispatch/journey/router.rb:32:in `serve'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/action_dispatch/routing/route_set.rb:882:in `call'](http://localhost:3000/account/edit#)
[bullet (7.1.1) lib/bullet/rack.rb:17:in `call'](http://localhost:3000/account/edit#)
[warden (1.2.9) lib/warden/manager.rb:36:in `block in call'](http://localhost:3000/account/edit#)
[warden (1.2.9) lib/warden/manager.rb:34:in `catch'](http://localhost:3000/account/edit#)
[warden (1.2.9) lib/warden/manager.rb:34:in `call'](http://localhost:3000/account/edit#)
[rack (3.0.8) lib/rack/tempfile_reaper.rb:20:in `call'](http://localhost:3000/account/edit#)
[rack (3.0.8) lib/rack/etag.rb:29:in `call'](http://localhost:3000/account/edit#)
[rack (3.0.8) lib/rack/conditional_get.rb:43:in `call'](http://localhost:3000/account/edit#)
[rack (3.0.8) lib/rack/head.rb:15:in `call'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/action_dispatch/http/permissions_policy.rb:36:in `call'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/action_dispatch/http/content_security_policy.rb:33:in `call'](http://localhost:3000/account/edit#)
[rack-session (2.0.0) lib/rack/session/abstract/id.rb:272:in `context'](http://localhost:3000/account/edit#)
[rack-session (2.0.0) lib/rack/session/abstract/id.rb:266:in `call'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/action_dispatch/middleware/cookies.rb:689:in `call'](http://localhost:3000/account/edit#)
[activerecord (7.1.0) lib/active_record/migration.rb:653:in `call'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'](http://localhost:3000/account/edit#)
[activesupport (7.1.0) lib/active_support/callbacks.rb:101:in `run_callbacks'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/action_dispatch/middleware/callbacks.rb:28:in `call'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/action_dispatch/middleware/executor.rb:14:in `call'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/action_dispatch/middleware/actionable_exceptions.rb:16:in `call'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/action_dispatch/middleware/debug_exceptions.rb:29:in `call'](http://localhost:3000/account/edit#)
[web-console (4.2.1) lib/web_console/middleware.rb:132:in `call_app'](http://localhost:3000/account/edit#)
[web-console (4.2.1) lib/web_console/middleware.rb:28:in `block in call'](http://localhost:3000/account/edit#)
[web-console (4.2.1) lib/web_console/middleware.rb:17:in `catch'](http://localhost:3000/account/edit#)
[web-console (4.2.1) lib/web_console/middleware.rb:17:in `call'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'](http://localhost:3000/account/edit#)
[railties (7.1.0) lib/rails/rack/logger.rb:37:in `call_app'](http://localhost:3000/account/edit#)
[railties (7.1.0) lib/rails/rack/logger.rb:24:in `block in call'](http://localhost:3000/account/edit#)
[activesupport (7.1.0) lib/active_support/tagged_logging.rb:135:in `block in tagged'](http://localhost:3000/account/edit#)
[activesupport (7.1.0) lib/active_support/tagged_logging.rb:39:in `tagged'](http://localhost:3000/account/edit#)
[activesupport (7.1.0) lib/active_support/tagged_logging.rb:135:in `tagged'](http://localhost:3000/account/edit#)
[activesupport (7.1.0) lib/active_support/broadcast_logger.rb:212:in `method_missing'](http://localhost:3000/account/edit#)
[railties (7.1.0) lib/rails/rack/logger.rb:24:in `call'](http://localhost:3000/account/edit#)
[sprockets-rails (3.4.2) lib/sprockets/rails/quiet_assets.rb:13:in `call'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/action_dispatch/middleware/remote_ip.rb:92:in `call'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/action_dispatch/middleware/request_id.rb:28:in `call'](http://localhost:3000/account/edit#)
[rack (3.0.8) lib/rack/method_override.rb:28:in `call'](http://localhost:3000/account/edit#)
[rack (3.0.8) lib/rack/runtime.rb:24:in `call'](http://localhost:3000/account/edit#)
[activesupport (7.1.0) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/action_dispatch/middleware/server_timing.rb:59:in `block in call'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/action_dispatch/middleware/server_timing.rb:24:in `collect_events'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/action_dispatch/middleware/server_timing.rb:58:in `call'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/action_dispatch/middleware/executor.rb:14:in `call'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/action_dispatch/middleware/static.rb:25:in `call'](http://localhost:3000/account/edit#)
[rack (3.0.8) lib/rack/sendfile.rb:114:in `call'](http://localhost:3000/account/edit#)
[actionpack (7.1.0) lib/action_dispatch/middleware/host_authorization.rb:141:in `call'](http://localhost:3000/account/edit#)
[railties (7.1.0) lib/rails/engine.rb:529:in `call'](http://localhost:3000/account/edit#)
[puma (6.4.0) lib/puma/configuration.rb:272:in `call'](http://localhost:3000/account/edit#)
[puma (6.4.0) lib/puma/request.rb:100:in `block in handle_request'](http://localhost:3000/account/edit#)
[puma (6.4.0) lib/puma/thread_pool.rb:378:in `with_force_shutdown'](http://localhost:3000/account/edit#)
[puma (6.4.0) lib/puma/request.rb:99:in `handle_request'](http://localhost:3000/account/edit#)
[puma (6.4.0) lib/puma/server.rb:443:in `process_client'](http://localhost:3000/account/edit#)
[puma (6.4.0) lib/puma/server.rb:241:in `block in run'](http://localhost:3000/account/edit#)
[puma (6.4.0) lib/puma/thread_pool.rb:155:in `block in spawn_thread'](http://localhost:3000/account/edit#)
```

**Comment by tonydefaria** [comment] 2023-10-13 17:23
And for my Devise routes I have this:

```
  # Devise routes
  devise_for :users, path: "account", controllers: {
    confirmations: "users/confirmations",
    passwords: "users/passwords",
    registrations: "users/registrations",
    sessions: "users/sessions"
  }, path_names: {
    sign_in: "login",
    sign_out: "logout",
    sign_up: "join"
  }
```

**Comment by excid3** [comment] 2023-10-13 17:49
Thanks! We have some code that only cancels active subscriptions when a user is deleted, so this will help us narrow down why that piece isn't working properly.

**Comment by tonydefaria** [comment] 2023-10-13 18:06
You are welcome and thank you for looking into this issue. :)

**Comment by excid3** [comment] 2023-10-13 18:31
Would you be able to snapshot the pay_subscription record and send that over too? Still am not able to replicate this quite right it seems.

Also, when you say...
>I advance the system clock to a day after the cancellation date.

Is that the Stripe test clock or your local machine's clock?

**Comment by tonydefaria** [comment] 2023-10-13 18:40
Stripe test clock.

**Comment by tonydefaria** [comment] 2023-10-13 18:46
I advance the clock 1 month and 1 day so the plan is cancelled in Stripe. Hope this makes sense.

**Comment by tonydefaria** [comment] 2023-10-13 18:48
And then I login my app and cancel the user. It's here I get the error. Apparently it can't find the subscription that has just been cancelled.

**Comment by excid3** [comment] 2023-10-13 19:01
Thanks! That's helpful.

Would you be able to screenshot the Pay::Subscription record from the Rails console so I can see the data?

**Comment by tonydefaria** [comment] 2023-10-13 19:19
Before cancelled in Stripe:

```
id: 6,
customer_id: 8,
name: "default",
processor_id: "sub_1O0qkoCychIMwryui5StvZDv",
processor_plan: "price_1NyxJCCychIMwryuyddJ4LZL",
quantity: 1,
status: "active",
current_period_start: Fri, 13 Oct 2023 20:10:16.000000000 BST +01:00,
current_period_end: Mon, 13 Nov 2023 19:10:16.000000000 GMT +00:00,
trial_ends_at: nil,
ends_at: nil,
metered: false,
pause_behavior: nil,
pause_starts_at: nil,
pause_resumes_at: nil,
application_fee_percent: nil,
metadata: {"email"=>"anderson9@test.com", "user_id"=>"10", "plan_name"=>"Whisper - test"},
data:
{"subscription_items"=>
  [{"id"=>"si_OoTi6ofgRqqDv7",
    "price"=>
      {"id"=>"price_1NyxJCCychIMwryuyddJ4LZL",
      "type"=>"recurring",
      "active"=>true,
      "object"=>"price",
      "created"=>1696772774,
      "product"=>"prod_OmWLBK4nwuB0gr",
      "currency"=>"usd",
      "livemode"=>false,
      "metadata"=>{},
      "nickname"=>nil,
      "recurring"=>{"interval"=>"month", "usage_type"=>"licensed", "interval_count"=>1, "aggregate_usage"=>nil, "trial_period_days"=>14},
      "lookup_key"=>"[FILTERED]",
      "tiers_mode"=>nil,
      "unit_amount"=>1200,
      "tax_behavior"=>"unspecified",
      "billing_scheme"=>"per_unit",
      "custom_unit_amount"=>nil,
      "transform_quantity"=>nil,
      "unit_amount_decimal"=>"1200"},
    "metadata"=>{},
    "quantity"=>1}]},
created_at: Fri, 13 Oct 2023 20:10:16.000000000 BST +01:00,
updated_at: Fri, 13 Oct 2023 20:10:39.087696000 BST +01:00,
prorate: true>

```

After cancelled in Stripe:

```
id: 6,
customer_id: 8,
name: "default",
processor_id: "sub_1O0qkoCychIMwryui5StvZDv",
processor_plan: "price_1NyxJCCychIMwryuyddJ4LZL",
quantity: 1,
status: "canceled",
current_period_start: Fri, 13 Oct 2023 20:10:16.000000000 BST +01:00,
current_period_end: Mon, 13 Nov 2023 19:10:16.000000000 GMT +00:00,
trial_ends_at: nil,
ends_at: Mon, 13 Nov 2023 19:10:16.000000000 GMT +00:00,
metered: false,
pause_behavior: nil,
pause_starts_at: nil,
pause_resumes_at: nil,
application_fee_percent: nil,
metadata: {"email"=>"anderson9@test.com", "user_id"=>"10", "plan_name"=>"Whisper - test"},
data:
{"subscription_items"=>
  [{"id"=>"si_OoTi6ofgRqqDv7",
    "price"=>
      {"id"=>"price_1NyxJCCychIMwryuyddJ4LZL",
      "type"=>"recurring",
      "active"=>true,
      "object"=>"price",
      "created"=>1696772774,
      "product"=>"prod_OmWLBK4nwuB0gr",
      "currency"=>"usd",
      "livemode"=>false,
      "metadata"=>{},
      "nickname"=>nil,
      "recurring"=>{"interval"=>"month", "usage_type"=>"licensed", "interval_count"=>1, "aggregate_usage"=>nil, "trial_period_days"=>14},
      "lookup_key"=>"[FILTERED]",
      "tiers_mode"=>nil,
      "unit_amount"=>1200,
      "tax_behavior"=>"unspecified",
      "billing_scheme"=>"per_unit",
      "custom_unit_amount"=>nil,
      "transform_quantity"=>nil,
      "unit_amount_decimal"=>"1200"},
    "metadata"=>{},
    "quantity"=>1}]},
created_at: Fri, 13 Oct 2023 20:10:16.000000000 BST +01:00,
updated_at: Fri, 13 Oct 2023 20:14:23.453564000 BST +01:00,
prorate: true>
```

And then when I delete the user in my app I get the infamous error :p

```
Pay::Stripe::Error in Users::RegistrationsController#destroy
No such subscription: 'sub_1O0qkoCychIMwryui5StvZDv'
```

**Comment by excid3** [comment] 2023-10-16 17:29
Alright, so the issue is that Pay currently considers `status: :canceled` as active if the `ends_at` is in the future. This was due to Braintree having no way to cancel a subscription during trial and continue giving them access until the end of the trial.

Since we will likely drop support for Braintree in the future, I think we'll considered all `status: :canceled` as as inactive, regardless of `ends_at`. Braintree subscriptions canceled during the trial will be ended immediately.

**Comment by tonydefaria** [comment] 2023-10-16 22:04
@excid3 Thank you for your time and patience for looking into this issue. So, for the time being I will keep my "dirty" solution until the changes are implemented in a future version.

**Comment by excid3** [comment] 2023-10-17 18:18
This should be fixed in `master`. We will be making a major version release soon that will include this.

**Closed by excid3** 2023-10-17 18:18 UTC
