### ISSUE TITLE
ActionController::RoutingError (uninitialized constant Pay::Webhooks::StripeController

### ISSUE THREAD

**Issue by guillaumebriday** [pay-rails/pay#306] opened 2021-04-11 22:36 UTC
Hey 👋 

On webhook callback, I have this error:

```ruby
ActionController::RoutingError (uninitialized constant Pay::Webhooks::StripeController
Did you mean?  DeviseController):
```

Here is my initializer:
```ruby
# frozen_string_literal: true

Pay.setup do |config|
  config.chargeable_class = 'Pay::Charge'
  config.chargeable_table = 'pay_charges'
  
 # For use in the receipt/refund/renewal mailers 
 # ...


  config.default_product_name = 'Gold'
  config.default_plan_name = 'gold'

  config.automount_routes = true
  config.routes_path = '/pay' # Only when automount_routes is true
end
```

And I don't have catchall routes.

I ran this command to forward hooks:

```bash
stripe listen --forward-to localhost:3000/pay/webhooks/stripe
```

I restarted my server many times and run bundle install too.

Any idea why?

Thanks!

**Comment by guillaumebriday** [comment] 2021-04-11 22:54
I think it's a cache issue, but I will try to make this problem reproducible.

**Comment by DavidColby** [comment] 2021-04-14 00:41
I'm experiencing this same error. For me, it happened when upgrading from pay 2.4.4 to the latest version. If I stay pinned to 2.4.4 I don't have this problem.

@guillaumebriday Were you able to find what was causing this for you?

**Comment by excid3** [comment] 2021-04-14 12:51
The class definitely exists: https://github.com/pay-rails/pay/blob/master/app/controllers/pay/webhooks/stripe_controller.rb

Maybe spring is caching something?

**Comment by DavidColby** [comment] 2021-04-14 15:23
@excid3 I figured it was a spring thing at first and I definitely killed spring (many times) with no change in behavior. I also deployed to a production server and replicated the error there so spring doesn't seem likely to be the culprit. Bumping from 2.4.4 to 2.6.0 causes the error right after a server restart, and bumping back down to 2.4.4 resolves the error after a server restart.

A little more investigation indicates this might be a Zeitwerk issue. If I add `config.autoloader = :classic` to `application.rb` the webhooks work as expected. Commenting that line out and rebooting the server causes the errors to occur again.

I think I've been able to resolve this without scrapping Zeitwerk by manually requiring pay in the pay initializer:

```ruby
require "pay/billable"
require "pay/stripe"
require "pay/webhooks"

Pay.setup do |config|
  config.chargeable_class = 'Charge'
  config.chargeable_table = 'pay_charges'
  # snip
end
```

I'm reaching the limits of my knowledge of Rails autoloading so perhaps there's something I'm missing in the setup that would make this change to the initializer unnecessary.

**Comment by excid3** [comment] 2021-04-14 15:29
Hmm, it's been working fine with Zeitwerk for me. Can you try running the test/dummy Rails app?

**Comment by DavidColby** [comment] 2021-04-14 16:12
Is there a guide on setting up the dummy app? I'm running into webpack issues after booting the server and bin/webpack-dev-server fails with `pay/test/dummy/Gemfile not found`. I'm probably missing something simple!

**Comment by excid3** [comment] 2021-04-14 16:27
```
bundle
cd test/dummy && rails s
```

**Comment by DavidColby** [comment] 2021-04-14 16:56
Thanks for your help, Chris, I appreciate the quick responses!

I ran the above commands on a fresh pull of pay and I'm getting the following error when I visit localhost:3000:

```
Puma caught this error: Webpacker can't find application.js in /Users/david/code/pay/test/dummy/public/packs-test/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
}
```

I'm traveling this afternoon and through the end of next week. I'm going to put this on the shelf until I'm back. I'll take another crack at it then and update here if I come across a solution. There must be something odd in my setup that's causing the Zeitwerk issues.

**Comment by clupprich** [comment] 2021-04-30 06:25
I'm seeing the same issue in our app. When enabling verbose logging for the zeitwerk loader (https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#troubleshooting), I'm not seeing the webhook controllers being autoloaded:

```
Zeitwerk@rails.main: autoload set for Pay::ApplicationController, to be loaded from /Users/christoph/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/pay-2.6.10/app/controllers/pay/application_controller.rb
Zeitwerk@rails.main: autoload set for Pay::PaymentsController, to be loaded from /Users/christoph/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/pay-2.6.10/app/controllers/pay/payments_controller.rb
Zeitwerk@rails.main: autoload set for Pay::ApplicationHelper, to be loaded from /Users/christoph/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/pay-2.6.10/app/helpers/pay/application_helper.rb
Zeitwerk@rails.main: autoload set for Pay::EmailSyncJob, to be loaded from /Users/christoph/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/pay-2.6.10/app/jobs/pay/email_sync_job.rb
Zeitwerk@rails.main: autoload set for Pay::ApplicationJob, to be loaded from /Users/christoph/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/pay-2.6.10/app/jobs/pay/application_job.rb
Zeitwerk@rails.main: autoload set for Pay::UserMailer, to be loaded from /Users/christoph/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/pay-2.6.10/app/mailers/pay/user_mailer.rb
Zeitwerk@rails.main: autoload set for Pay::ApplicationMailer, to be loaded from /Users/christoph/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/pay-2.6.10/app/mailers/pay/application_mailer.rb
Zeitwerk@rails.main: autoload set for Pay::Charge, to be loaded from /Users/christoph/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/pay-2.6.10/app/models/pay/charge.rb
Zeitwerk@rails.main: autoload set for Pay::Subscription, to be loaded from /Users/christoph/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/pay-2.6.10/app/models/pay/subscription.rb
Zeitwerk@rails.main: autoload set for Pay::ApplicationRecord, to be loaded from /Users/christoph/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/pay-2.6.10/app/models/pay/application_record.rb
```

I'll spend some time this morning to get the dummy application up and running and replicate there (right now running into migration issues).

**Comment by jackspiva** [comment] 2021-11-16 20:53
Hm I'm running into this as well (adding `config.autoloader = :classic` to my `application.rb` also made the problem go away). I tried the dummy app, but it ran fine :/. 

Any suggestions for where to go from here? I'm happy to give more info if that would be helpful.

**Comment by jackspiva** [comment] 2021-11-18 16:32
@clupprich @DavidColby @guillaumebriday did any of y'all ever find the source of your problem / a workaround?

**Comment by excid3** [comment] 2021-11-18 16:37
@jackspiva What versions of Pay and Zeitwerk are you on? And can you create an example repo that has the error?

**Comment by jackspiva** [comment] 2021-11-18 17:11
I'm on `pay (3.0.23)` and `zeitwerk (2.4.2)`, and I finally figured out how to reproduce it! https://github.com/jackspiva/pay is giving me the same error as we're seeing in our application. 

I am confused by why the change would be causing the error though. The only real change from the default dummy app was adding:

```
config.load_defaults "6.0" # enables zeitwerk mode in CRuby
```

to `application.rb`. I don't have a great understanding of the zeitwerk changes from Rails 6, but my impression was that that line wasn't even really necessary as zeitwerk is enabled by default now. Any idea what's going on here? Also, thanks for reaching out!

**Comment by excid3** [comment] 2021-11-18 17:25
I don't know exactly what's going on, but we can probably add a controller test that replicates this and then find a good way to fix it.

**Comment by jackspiva** [comment] 2021-11-18 18:03
It seems that just adding `config.autoloader = :zeitwerk` to the `application.rb` causes the issue as well. So that's probably the part from the 6.0 defaults that's breaking it.  

https://github.com/jackspiva/pay/commit/86ca6d6aed4fd413cf213b6ed0cbd604ec1cec81.

I'm happy to try adding a controller test, but not totally sure how to go about it. I know that adding `config.autoloader = :zeitwerk` causes the existing controller tests to fail, but were you thinking a test that updates the application config and then tries a request to a controller? I'm not totally sure how that would work / if that's possible.

**Comment by jackspiva** [comment] 2021-11-18 19:24
I can also confirm what @clupprich said about moving the webhook controllers to a different namespace seeming to fix the issue. I tried it here [40d4459](https://github.com/jackspiva/pay/commit/40d4459c3a1e177f63c5753fa331672066f38a8a) and the tests are now passing.

**Comment by excid3** [comment] 2021-11-19 03:38
Yeah, I guess defining the module in `lib/pay.rb` affects Zeitwerk's lookup with the autoloaded Rails folder?

**Comment by jackspiva** [comment] 2021-11-19 15:24
Hm that does look promising, but I get this error when trying to run it:

```ruby
ArgumentError: wrong number of arguments (given 1, expected 0)
    zeitwerk (2.4.2) lib/zeitwerk/loader.rb:392:in `eager_load'
```

seems like `loader.eager_load(force: true)` doesn't expect any arguments? It passes when I remove the `force: true`, so it doesn't seem to be catching it :/.

**Comment by excid3** [comment] 2021-11-19 16:42
Maybe it changed in Zeitwerk 2.5?

**Comment by jackspiva** [comment] 2021-11-19 21:08
Ah yeah looks like it was added in Zeitwerk 2.5. I tried upgrading to 2.5 and added a test like:

```
test "zeitwerk compliance" do
    loader = Zeitwerk::Loader.new

    begin
      loader.eager_load(force: true)
    rescue Zeitwerk::NameError => e
      flunk e.message
    else
      assert true
    end
end
```

and it passed even with the issue. Not sure if I need to be configuring the loader in a certain way after I initialize it to make it pick up the issue though.

**Comment by jackspiva** [comment] 2022-02-08 22:26
@guillaumebriday @excid3 upgrading from `3.0.23` to `3.0.24` fixed this for me! You can probably close this issue unless others are still running into this.

**Comment by excid3** [comment] 2022-02-08 22:38
Awesome, feel free to open a new issue if the persists.

**Closed by excid3** 2022-02-08 22:38 UTC
