### ISSUE TITLE
Stripe cancel now doesn't correctly update local records

### ISSUE THREAD

**Issue by doutatsu** [pay-rails/pay#350] opened 2021-06-03 22:02 UTC
When cancelling a Stripe subscription, all works correctly - `ends_at` gets set to the end of the billing period. But when I then go and cancel the subscription _now_, it doesn't seem to correctly update the records. Here is the webhook:

```json
  Parameters: {"id"=>"evt_1IyOPfDVmQzTIthFMVFdRi7X", "object"=>"event", "api_version"=>"2020-03-02", "created"=>1622756955, "data"=>{"object"=>{"id"=>"sub_JbbSO6yLqKwSyt", "object"=>"subscription", "application_fee_percent"=>nil, "billing_cycle_anchor"=>1622756324, "billing_thresholds"=>nil, "cancel_at"=>1625348324, "cancel_at_period_end"=>true, "canceled_at"=>1622756954, "collection_method"=>"charge_automatically", "created"=>1622756324, "current_period_end"=>1625348324, "current_period_start"=>1622756324, "customer"=>"cus_JbDCr2umcVH5JT", "days_until_due"=>nil, "default_payment_method"=>"pm_1IyOAkDVmQzTIthFRA8mW4kq", "default_source"=>nil, "default_tax_rates"=>[], "discount"=>nil, "ended_at"=>nil, "items"=>{"object"=>"list", "data"=>[{"id"=>"si_JbbS2JgD13RpNi", "object"=>"subscription_item", "billing_thresholds"=>nil, "created"=>1622756325, "metadata"=>{}, "plan"=>{"id"=>"price_1IwoIODVmQzTIthFGcUHo6kS", "object"=>"plan", "active"=>true, "aggregate_usage"=>nil, "amount"=>200, "amount_decimal"=>"200", "billing_scheme"=>"per_unit", "created"=>1622379792, "currency"=>"gbp", "interval"=>"month", "interval_count"=>1, "livemode"=>false, "metadata"=>{}, "nickname"=>nil, "product"=>"lite", "tiers"=>nil, "tiers_mode"=>nil, "transform_usage"=>nil, "trial_period_days"=>nil, "usage_type"=>"licensed"}, "price"=>{"id"=>"price_1IwoIODVmQzTIthFGcUHo6kS", "object"=>"price", "active"=>true, "billing_scheme"=>"per_unit", "created"=>1622379792, "currency"=>"gbp", "livemode"=>false, "lookup_key"=>nil, "metadata"=>{}, "nickname"=>nil, "product"=>"lite", "recurring"=>{"aggregate_usage"=>nil, "interval"=>"month", "interval_count"=>1, "trial_period_days"=>nil, "usage_type"=>"licensed"}, "tiers_mode"=>nil, "transform_quantity"=>nil, "type"=>"recurring", "unit_amount"=>200, "unit_amount_decimal"=>"200"}, "quantity"=>1, "subscription"=>"sub_JbbSO6yLqKwSyt", "tax_rates"=>[]}], "has_more"=>false, "total_count"=>1, "url"=>"/v1/subscription_items?subscription=sub_JbbSO6yLqKwSyt"}, "latest_invoice"=>"in_1IyOFUDVmQzTIthFr2lEoX0W", "livemode"=>false, "metadata"=>{}, "next_pending_invoice_item_invoice"=>nil, "pause_collection"=>nil, "pending_invoice_item_interval"=>nil, "pending_setup_intent"=>nil, "pending_update"=>nil, "plan"=>{"id"=>"price_1IwoIODVmQzTIthFGcUHo6kS", "object"=>"plan", "active"=>true, "aggregate_usage"=>nil, "amount"=>200, "amount_decimal"=>"200", "billing_scheme"=>"per_unit", "created"=>1622379792, "currency"=>"gbp", "interval"=>"month", "interval_count"=>1, "livemode"=>false, "metadata"=>{}, "nickname"=>nil, "product"=>"lite", "tiers"=>nil, "tiers_mode"=>nil, "transform_usage"=>nil, "trial_period_days"=>nil, "usage_type"=>"licensed"}, "quantity"=>1, "schedule"=>nil, "start_date"=>1622756324, "status"=>"active", "tax_percent"=>nil, "transfer_data"=>nil, "trial_end"=>nil, "trial_start"=>nil}, "previous_attributes"=>{"cancel_at"=>nil, "cancel_at_period_end"=>false, "canceled_at"=>nil}}, "livemode"=>false, "pending_webhooks"=>2, "request"=>{"id"=>nil, "idempotency_key"=>nil}, "type"=>"customer.subscription.updated", "stripe"=>{"id"=>"evt_1IyOPfDVmQzTIthFMVFdRi7X", "object"=>"event", "api_version"=>"2020-03-02", "created"=>1622756955, "data"=>{"object"=>{"id"=>"sub_JbbSO6yLqKwSyt", "object"=>"subscription", "application_fee_percent"=>nil, "billing_cycle_anchor"=>1622756324, "billing_thresholds"=>nil, "cancel_at"=>1625348324, "cancel_at_period_end"=>true, "canceled_at"=>1622756954, "collection_method"=>"charge_automatically", "created"=>1622756324, "current_period_end"=>1625348324, "current_period_start"=>1622756324, "customer"=>"cus_JbDCr2umcVH5JT", "days_until_due"=>nil, "default_payment_method"=>"pm_1IyOAkDVmQzTIthFRA8mW4kq", "default_source"=>nil, "default_tax_rates"=>[], "discount"=>nil, "ended_at"=>nil, "items"=>{"object"=>"list", "data"=>[{"id"=>"si_JbbS2JgD13RpNi", "object"=>"subscription_item", "billing_thresholds"=>nil, "created"=>1622756325, "metadata"=>{}, "plan"=>{"id"=>"price_1IwoIODVmQzTIthFGcUHo6kS", "object"=>"plan", "active"=>true, "aggregate_usage"=>nil, "amount"=>200, "amount_decimal"=>"200", "billing_scheme"=>"per_unit", "created"=>1622379792, "currency"=>"gbp", "interval"=>"month", "interval_count"=>1, "livemode"=>false, "metadata"=>{}, "nickname"=>nil, "product"=>"lite", "tiers"=>nil, "tiers_mode"=>nil, "transform_usage"=>nil, "trial_period_days"=>nil, "usage_type"=>"licensed"}, "price"=>{"id"=>"price_1IwoIODVmQzTIthFGcUHo6kS", "object"=>"price", "active"=>true, "billing_scheme"=>"per_unit", "created"=>1622379792, "currency"=>"gbp", "livemode"=>false, "lookup_key"=>nil, "metadata"=>{}, "nickname"=>nil, "product"=>"lite", "recurring"=>{"aggregate_usage"=>nil, "interval"=>"month", "interval_count"=>1, "trial_period_days"=>nil, "usage_type"=>"licensed"}, "tiers_mode"=>nil, "transform_quantity"=>nil, "type"=>"recurring", "unit_amount"=>200, "unit_amount_decimal"=>"200"}, "quantity"=>1, "subscription"=>"sub_JbbSO6yLqKwSyt", "tax_rates"=>[]}], "has_more"=>false, "total_count"=>1, "url"=>"/v1/subscription_items?subscription=sub_JbbSO6yLqKwSyt"}, "latest_invoice"=>"in_1IyOFUDVmQzTIthFr2lEoX0W", "livemode"=>false, "metadata"=>{}, "next_pending_invoice_item_invoice"=>nil, "pause_collection"=>nil, "pending_invoice_item_interval"=>nil, "pending_setup_intent"=>nil, "pending_update"=>nil, "plan"=>{"id"=>"price_1IwoIODVmQzTIthFGcUHo6kS", "object"=>"plan", "active"=>true, "aggregate_usage"=>nil, "amount"=>200, "amount_decimal"=>"200", "billing_scheme"=>"per_unit", "created"=>1622379792, "currency"=>"gbp", "interval"=>"month", "interval_count"=>1, "livemode"=>false, "metadata"=>{}, "nickname"=>nil, "product"=>"lite", "tiers"=>nil, "tiers_mode"=>nil, "transform_usage"=>nil, "trial_period_days"=>nil, "usage_type"=>"licensed"}, "quantity"=>1, "schedule"=>nil, "start_date"=>1622756324, "status"=>"active", "tax_percent"=>nil, "transfer_data"=>nil, "trial_end"=>nil, "trial_start"=>nil}, "previous_attributes"=>{"cancel_at"=>nil, "cancel_at_period_end"=>false, "canceled_at"=>nil}}, "livemode"=>false, "pending_webhooks"=>2, "request"=>{"id"=>nil, "idempotency_key"=>nil}, "type"=>"customer.subscription.updated"}}
```

and the only result was the update `ends_at` at the end of the billing period, not right now:
`Pay::Subscription Update (0.8ms)  UPDATE "pay_subscriptions" SET "ends_at" = $1, "updated_at" = $2 WHERE "pay_subscriptions"."id" = $3  [["ends_at", "2021-07-03 21:38:44"], ["updated_at", "2021-06-03 21:49:16.120390"], ["id", 1]]`

If I then try to cancel_now through console, I obviously see that subscription doesn't exist anymore
![image](https://user-images.githubusercontent.com/4270980/120717441-72dfcf80-c4bf-11eb-834e-555246cbc39a.png)

**Comment by excid3** [comment] 2021-06-03 22:07
Can you share the steps to reproduce?

**Comment by doutatsu** [comment] 2021-06-05 16:10
Should be as simple as:
1. Use checkout to subscribe to a plan (monthly in my case)
2. Subscription will be correctly created as active from the webhook
3. Go to the Stripe dashboard, select subscription created, click "Cancel subscription" and then choose "Immediately"
4. Observe a webhook come in **but no change to the subscription happen**

**Comment by doutatsu** [comment] 2021-06-06 13:40
I've tried some things to confirm, and the above is incorrect. When you create a subscription and then cancel it, immediately - everything works as expected.

But if you create a subscription, then cancel it regularly (so that it stays active till the end of billing period), **then go into Stripe and cancel immediately**, that's when the database won't update.

Looking into webhooks, unlike how it works for a regular cancellation, you get subscription deleted webhook as well:
```
2021-06-06 14:37:03   --> customer.subscription.updated [evt_1IzM9wDVmQzTIthFWXvguAWq]
2021-06-06 14:37:03  <--  [200] POST http://localhost:3000/pay/webhooks/stripe [evt_1IzM9wDVmQzTIthFWXvguAWq]
2021-06-06 14:37:30   --> customer.subscription.deleted [evt_1IzMAQDVmQzTIthFMTEasEj0]
2021-06-06 14:37:30  <--  [200] POST http://localhost:3000/pay/webhooks/stripe [evt_1IzMAQDVmQzTIthFMTEasEj0]
```

**Comment by doutatsu** [comment] 2021-06-08 13:18
I've managed to figured out most other things now, so this seems to be the last thing I am worried about. If you don't get a chance to look into it, I'll see if I can dig into pay gem myself, to see what's the cause of this

**Comment by ihsaneddin** [comment] 2021-07-26 17:07
I think the problem is on
`Pay::Billable.includers` 
returns blank array, so the owner is missing on Pay::Stripe::Subscription#sync method. I tried this on local. Only after I add code to call Billable model it works. Maybe it the development env on rails is not eager loading all model classes.

**Comment by excid3** [comment] 2021-08-20 00:13
Yeah, that's probably the issue. If the model hasn't been loaded in development, then it wouldn't be found by the webhook. 

This is fixed in Pay v3 as we're moving things to a `Pay::Customer` model and we no longer have to keep track of which models include Billable. 👍

**Closed** 2021-10-03 17:03 UTC
