### ISSUE TITLE
Job Proliferation

### ISSUE THREAD

**Issue by ykamin-booth** [pay-rails/pay#438] opened 2021-09-15 08:32 UTC
Hi, I'm getting a ton of mailer jobs added to the delayed_jobs table (I think it's just happening when I call the refund! method on a Pay::Charge object, though it may have also happened when I created a charge). 

![image](https://user-images.githubusercontent.com/63565816/133398970-477068b5-07fd-4d02-a289-e820d6d1894c.png)

Here is an example handler:

`--- !ruby/object:ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper job_data: job_class: ActionMailer::MailDeliveryJob job_id: f1e377f8-e0ad-4afd-9135-5e6b4e054514 provider_job_id: queue_name: mailers priority: arguments: - Pay::UserMailer - receipt - deliver_now - params: pay_customer: _aj_globalid: gid://neesh-attempt2/Pay::Customer/18 charge: _aj_globalid: gid://neesh-attempt2/Pay::Charge/63 _aj_symbol_keys: - pay_customer - charge args: [] _aj_symbol_keys: - params - args executions: 0 exception_executions: {} locale: en timezone: UTC enqueued_at: '2021-09-15T08:02:01Z' `

**Comment by ykamin-booth** [comment] 2021-09-15 08:40
Another handler, this one actually for a refund. The fact that the previous was for a receipt seems to imply that it's not just happening with the refund method;

`--- !ruby/object:ActiveJob::QueueAdapters::DelayedJobAdapter::JobWrapper job_data: job_class: ActionMailer::MailDeliveryJob job_id: 4d2262ba-dda2-4a7b-acd7-45db24a07faa provider_job_id: queue_name: mailers priority: arguments: - Pay::UserMailer - refund - deliver_now - params: pay_customer: _aj_globalid: gid://neesh-attempt2/Pay::Customer/18 charge: _aj_globalid: gid://neesh-attempt2/Pay::Charge/64 _aj_symbol_keys: - pay_customer - charge args: [] _aj_symbol_keys: - params - args executions: 0 exception_executions: {} locale: en timezone: UTC enqueued_at: '2021-09-15T08:38:22Z'`

**Comment by excid3** [comment] 2021-09-15 13:21
Emails are sent for each new charges and refunds. You'll have to send me some more details about what's wrong.

**Comment by ykamin-booth** [comment] 2021-09-15 22:31
Sure. It's happening inconsistently, but I can confirm it's happening for both generating and refunding Pay::Charges. We're talking about hundreds of jobs for a single charge or refund. 

I'm generating charges via stripe checkout sessions, and they are coming in off of the Stipe CLI webhooks in my test environment. I'm attaching two CSVs, The first is the delayed_jobs table after creating a charge, the second is after issuing a refund by calling the refund! method. The charges are being created and refunded successfully. 

[delayed_jobs_receipt.csv](https://github.com/pay-rails/pay/files/7173583/delayed_jobs_receipt.csv)
[delayed_jobs_refund.csv](https://github.com/pay-rails/pay/files/7173619/delayed_jobs_refund.csv)

What other info do you need from me?

**Comment by excid3** [comment] 2021-09-16 12:38
If you can figure out a way for me to reproduce this, that would be amazing.

Here's the test where we ensure it only enqueues one receipt email job: https://github.com/pay-rails/pay/blob/master/test/pay/stripe/webhooks/charge_succeeded_test.rb#L14

**Comment by excid3** [comment] 2021-09-16 18:51
I don't know if #439 solves your issue, but that could be related and why it started a bunch of jobs if it was retrying them after failing.

**Comment by ykamin-booth** [comment] 2021-09-19 07:26
Unfortunately it didn't solve the issue. One thing I've noticed is that more jobs seems to be created the more I create and refund charges with the same customer.

**Comment by excid3** [comment] 2021-09-19 13:18
Alright, well with more information about the situation, I'm not sure I can do much more.

**Comment by ykamin-booth** [comment] 2021-09-20 12:22
Some other possibly relevant information. The concern that extends the Pay::Charge model has a before_save action and two after_create actions. The before_save action saves information from the charge metadata to an additional custom column in the pay_charge table to associate the charge with another model, and the after_create actions include one that broadcasts info about the charge to a channel. I’d guess the former is a likely culprit but unfortunately I’m away on vacation and can’t test it right now.

**Comment by ykamin-booth** [comment] 2021-10-05 21:46
Here is the ChargeExtension concern:

```
module ChargeExtensions
  extend ActiveSupport::Concern

  included do
    belongs_to(:event, { :required => false, :class_name => "Event", :foreign_key => "event_id" })
    scope :unrefunded, -> { where(:amount_refunded => 0) }
    has_one :payer, through: :customer, source: :owner, source_type: "User"
    has_one :recipient, through: :event, source: :creator
    before_save :add_event
    after_create :add_paying_guest_to_attending
    after_create :broadcast_payment_action_cable
  end

  def add_event
    event_id=self.metadata["event_id"].to_i
    self.event_id=event_id
  end
  
  def add_paying_guest_to_attending
    event=self.event
    event.add_user_to_attending(self.payer)
  end
  
  def broadcast_payment_action_cable
    PaymentsChannel.broadcast_to self.payer, charge_id: self.id
  end
  
end
```

For now my workaround is to turn off emails in the pay configuration, which prevents the problem.

**Comment by rathboma** [comment] 2021-11-09 02:48
I'm having the same issue.

I start a new test subscription. End the trial, trigger the first payment. There is a single charge in the pay_charges table, and a single charge in the stripe dashboard, but my app sends 15 emails!

@excid3 Any ideas?

I can see all the 15 jobs go through the worker, they all complete fine.

![image](https://user-images.githubusercontent.com/279769/140852560-11f02325-3181-49cd-b6b4-e75fbc0aa2b9.png)


![image](https://user-images.githubusercontent.com/279769/140852612-afb25e95-1c60-448c-8d9e-22a9317f59ce.png)



![image](https://user-images.githubusercontent.com/279769/140852515-16faaa15-cbb4-4c00-8173-b736f24289e2.png)

**Comment by excid3** [comment] 2021-11-09 14:38
Share some more details and/or a way to replicate the issue. 👍

**Comment by rathboma** [comment] 2021-11-10 23:43
@excid3 Let me see if I can replicate

**Comment by rathboma** [comment] 2021-11-15 19:49
@excid3 Here's is a basic rails app that replicates this issue:
https://github.com/beekeeper-studio/pay-emails-example

To replicate:
1. Add your stripe test creds to .env, add PORT=3000 to .env
2. bin/rails db:migrate
3. foreman start
4. note the stripe signing secret, add to .env, restart processes
5. bin/rails c, create a user then sign them up to a subscription.
6. Go to localhost:3100, see you have received 5-19 receipt emails

I've noticed if you sign them up for a trial first, then end the trial in the stripe UI it sends more emails.

**Comment by rathboma** [comment] 2021-11-18 21:34
Here's a screenshot. It's running `ProcessJob` 'once', but looks like ChargeSucceeded is getting called 19 times? Or at least it's executing 19 times.

![image](https://user-images.githubusercontent.com/279769/142500330-6936ddcf-f3e6-4473-83d1-f7fcf3a81fc2.png)

**Comment by excid3** [comment] 2021-11-18 21:40
Can you inspect the job and see if there's an error causing it to retry?

**Comment by rathboma** [comment] 2021-11-18 21:42
Here's what's happening - `configure_webhooks` is being called over and over:

![image](https://user-images.githubusercontent.com/279769/142501415-04326c05-b387-4844-81ad-a9d714a82d02.png)

**Comment by rathboma** [comment] 2021-11-18 21:43
(I added a puts to lib/pay/stripe.rb#configure_webhooks)

I'm using delayed_job as the worker library. It this due to hotloading or something like that?

I'm pretty rusty on my rails preload knowledge, but feels like something like that?

**Comment by rathboma** [comment] 2021-11-18 21:45
Looks like this is the cause (in the default `development.rb`):

```
  # Do not eager load code on boot.
  config.eager_load = false
```

**Comment by rathboma** [comment] 2021-11-18 21:59
So this works as a patch to `delegator.rb`, but not sure this is very idiomatic?

```ruby
      # Configure DSL
      def configure(id, &block)
        return if @ids.include?(id)
        @ids << id
        raise ArgumentError, "must provide a block" unless block
        block.arity.zero? ? instance_eval(&block) : yield(self)
      end
```

Use it like:

```ruby
Pay::Webhooks.configure('stripe') do |config|
 ...
end

```

**Comment by rathboma** [comment] 2021-11-23 17:29
@excid3 Please let me know what you think we should do here, it makes Pay almost unusable in dev mode

**Comment by rathboma** [comment] 2022-02-02 02:39
@excid3 Would love your feedback on the above ^?

**Comment by excid3** [comment] 2022-02-02 21:20
Doh! Somehow missed that. I will take a look finally. :)

**Comment by excid3** [comment] 2022-02-03 20:44
This should be fixed in bcfb63f

DelayedJob seems to be causing reloads of Rails (not sure why) which re-adds event listeners to the webhooks each time.

**Comment by rathboma** [comment] 2022-02-03 21:06
you rock! Didn't realize this was delayed job specific. Thanks so much for fixing.

**Comment by excid3** [comment] 2022-02-03 21:22
It would have been affecting other things, so this will be a great bug to have finally fixed.

Did you test and confirm that fixes it for you?

**Comment by rathboma** [comment] 2022-02-15 21:30
Good timing! I actually just tested it last night. Looks good! Thanks so much!

**Closed** 2022-02-15 22:15 UTC
Labels: bug
